### ISSUE TITLE
Buttons and blockquotes

### ISSUE THREAD

**Issue by cranmer** [UW-Madison-DSI/uw-jekyll-theme#10]
Integrate UW style buttons and blockquotes 

https://brand.wisc.edu/uwmadison_templates/

**Comment by amegahed** [comment]
This should have been addressed by the inclusion of the default UW template styles.  See the blog post "default UW template styles" for details:
http://127.0.0.1:4000/uw-jekyll-theme/blog/2024/default-styles/

**Comment by cranmer** [comment]
Nice, thanks! The example post is all written in html. I'm curious how one would indicate this styling in a more markdown oriented syntax. 

This might be relevant:
https://boringrails.com/tips/jekyll-css-class

**Comment by cranmer** [comment]
we might want to add a special liquid tag for blockquotes

**Comment by cranmer** [comment]
For reference, the source is here:
https://github.com/UW-Madison-DSI/uw-jekyll-theme/blob/master/_posts/2023-05-28-default-styles.md

**Comment by cranmer** [comment]
ok, so this works:

```
## Test h2 and blockquote style with markdown syntax
{: .uw-mini-bar}

> "All models are wrong but some are useful"
<cite>George Box</cite>

>   “Whatever may be the limitations which trammel inquiry elsewhere, we believe that the great state University of Wisconsin should ever encourage that continual and fearless sifting and winnowing by which alone the truth can be found.”
<cite>The Board of Regents, 1894</cite>
{: .uw-stylized-quote}


```
