### ISSUE TITLE
Update README for UW audience.

### ISSUE THREAD

**Issue by cranmer** [UW-Madison-DSI/uw-jekyll-theme#11]
The current README is from the al-folio repository. It would be good to keep some instructions and examples, but also make the README more customized for a UW audience. For example:

 * intro to the basic idea that this is meant to be a static alternative to wiscweb 
 * update example images to look like what you get with the base installation

**Comment by amegahed** [comment]
Added a simple README with a description of features, instructions for running, and license info.
