### ISSUE TITLE
Integrate features of UW theme

### ISSUE THREAD

**Issue by cranmer** [UW-Madison-DSI/uw-jekyll-theme#6]
add liquid tag for the large text and the centered heading like "Our Program"  from within the markdown of a post.

<img width="690" alt="image" src="https://github.com/UW-Madison-DSI/uw-jekyll-theme/assets/4458890/06c01cc5-3764-41c6-9ac3-d3a284ae733b">

**Comment by amegahed** [comment]
Updated headings to use centered style with UW red "mini-bar".

![projects](https://github.com/UW-Madison-DSI/uw-jekyll-theme/assets/8449604/6cc67b3d-b009-4242-94c1-1d8971735388)
