### ISSUE TITLE
includes / liquid tags for hero image

### ISSUE THREAD

**Issue by cranmer** [UW-Madison-DSI/uw-jekyll-theme#9]
Add include and liquid tags so one can include a hero image into a page. 
Maybe add a specialized page type in the `_layouts` director where the hero image is specified in the header of the the markdown similar to how the [about page type can specify an image and address for a person's profile](https://raw.githubusercontent.com/alshedivat/al-folio/master/_pages/about.md)

<img width="1350" alt="image" src="https://github.com/UW-Madison-DSI/uw-jekyll-theme/assets/4458890/ffe22bb1-7d23-4c06-a35a-c101f005f7b6">

**Comment by amegahed** [comment]
I added an option to include a hero image to the default page template.  For example:

---
layout: about
title: about
hero: assets/images/hero-1550x370.jpg

![home](https://github.com/UW-Madison-DSI/uw-jekyll-theme/assets/8449604/e8f56f24-8c62-4929-a702-c42ace6a7f37)

**Comment by amegahed** [comment]
Here's an example:
![home](https://github.com/UW-Madison-DSI/uw-jekyll-theme/assets/8449604/da35e06d-9328-44aa-b4b1-85ea67080eed)

**Comment by cranmer** [comment]
Nice! Thanks

On May 29, 2024, at 10:38 AM, Abe Megahed ***@***.***> wrote:

﻿

Here's an example:
home.png (view on web)<https://github.com/UW-Madison-DSI/uw-jekyll-theme/assets/8449604/da35e06d-9328-44aa-b4b1-85ea67080eed>
